export { default as Navbar } from './navbar/Navbar.jsx'
export { default as Hero } from './hero/Hero.jsx'
export { default as Hero2 } from './hero2/Hero2.jsx'
export { default as Hero3 } from './hero3/Hero3.jsx'
export { default as Footer } from './footer/Footer.jsx'
